require:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 150
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*'
Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - test
    - development
Style/FrozenStringLiteralComment:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 6
RSpec/InstanceVariable:
  Enabled: false
Metrics/ClassLength:
  Max: 100
RSpec/ExampleLength:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/AbcSize:
  Max: 32
Style/Documentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

AllCops:
  NewCops: enable
  Exclude:
    - 'db/data_schema.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'db/seeds/*'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'Guardfile'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'app/models/concerns/belongs_to_non_db.rb'
    - 'lib/file_lock.rb'
    - 'lib/tasks/*'